"""Permission codes and role→permission mappings for ClinicTraq RBAC."""

# ── Patient permissions ──────────────────────────────────────────────────────
PERM_PATIENTS_VIEW = "patients:view"
PERM_PATIENTS_CREATE = "patients:create"
PERM_PATIENTS_EDIT_DEMOGRAPHICS = "patients:edit_demographics"
PERM_PATIENTS_EDIT_INSURANCE = "patients:edit_insurance"
PERM_PATIENTS_VIEW_PHI = "patients:view_phi"
PERM_PATIENTS_MERGE = "patients:merge"

# ── Scheduling permissions ────────────────────────────────────────────────────
PERM_SCHEDULE_VIEW = "schedule:view"
PERM_SCHEDULE_BOOK = "schedule:book"
PERM_SCHEDULE_CANCEL = "schedule:cancel"
PERM_SCHEDULE_MANAGE = "schedule:manage"  # override slots, manage templates

# ── Clinical permissions ──────────────────────────────────────────────────────
PERM_CLINICAL_ROOM_PATIENT = "clinical:room_patient"      # vitals, intake, chief complaint
PERM_CLINICAL_VIEW_NOTES = "clinical:view_notes"
PERM_CLINICAL_DRAFT_NOTES = "clinical:draft_notes"        # scribes
PERM_CLINICAL_SIGN_NOTES = "clinical:sign_notes"          # providers only
PERM_CLINICAL_EDIT_PROBLEMS = "clinical:edit_problems"
PERM_CLINICAL_EDIT_MEDICATIONS = "clinical:edit_medications"
PERM_CLINICAL_EDIT_ALLERGIES = "clinical:edit_allergies"
PERM_CLINICAL_PLACE_ORDERS = "clinical:place_orders"
PERM_CLINICAL_SIGN_ORDERS = "clinical:sign_orders"        # providers only
PERM_CLINICAL_PRESCRIBE = "clinical:prescribe"            # providers only
PERM_CLINICAL_VIEW_RESULTS = "clinical:view_results"
PERM_CLINICAL_RELEASE_RESULTS = "clinical:release_results"  # providers only
PERM_CLINICAL_BODY_MAP = "clinical:body_map"

# ── Billing permissions ──────────────────────────────────────────────────────
PERM_BILLING_VIEW_CHARGES = "billing:view_charges"
PERM_BILLING_ENTER_CHARGES = "billing:enter_charges"
PERM_BILLING_EDIT_CHARGES = "billing:edit_charges"
PERM_BILLING_VIEW_CLAIMS = "billing:view_claims"
PERM_BILLING_SUBMIT_CLAIMS = "billing:submit_claims"
PERM_BILLING_CORRECT_CLAIMS = "billing:correct_claims"
PERM_BILLING_POST_PAYMENTS = "billing:post_payments"
PERM_BILLING_POST_ADJUSTMENTS = "billing:post_adjustments"
PERM_BILLING_WRITE_OFF = "billing:write_off"              # requires manager approval above threshold
PERM_BILLING_ISSUE_REFUNDS = "billing:issue_refunds"
PERM_BILLING_WORK_DENIALS = "billing:work_denials"
PERM_BILLING_FILE_APPEALS = "billing:file_appeals"
PERM_BILLING_VIEW_AR = "billing:view_ar"
PERM_BILLING_VIEW_ERA = "billing:view_era"
PERM_BILLING_IMPORT_ERA = "billing:import_era"
PERM_BILLING_PATIENT_STATEMENTS = "billing:patient_statements"
PERM_BILLING_PATIENT_PAYMENTS = "billing:patient_payments"  # collect copays/self-pay

# ── Eligibility permissions ───────────────────────────────────────────────────
PERM_ELIGIBILITY_CHECK = "eligibility:check"
PERM_ELIGIBILITY_VIEW = "eligibility:view"

# ── Document permissions ──────────────────────────────────────────────────────
PERM_DOCUMENTS_UPLOAD = "documents:upload"
PERM_DOCUMENTS_VIEW = "documents:view"
PERM_DOCUMENTS_DELETE = "documents:delete"  # admin only

# ── Settings / admin permissions ──────────────────────────────────────────────
PERM_SETTINGS_VIEW = "settings:view"
PERM_SETTINGS_EDIT_PRACTICE = "settings:edit_practice"
PERM_SETTINGS_MANAGE_USERS = "settings:manage_users"
PERM_SETTINGS_MANAGE_PROVIDERS = "settings:manage_providers"
PERM_SETTINGS_MANAGE_PAYERS = "settings:manage_payers"
PERM_SETTINGS_MANAGE_FEE_SCHEDULES = "settings:manage_fee_schedules"
PERM_SETTINGS_MANAGE_ROLES = "settings:manage_roles"

# ── Org / hierarchy permissions ───────────────────────────────────────────────
PERM_ORG_VIEW_CLINICS = "org:view_clinics"
PERM_ORG_MANAGE_CLINICS = "org:manage_clinics"
PERM_ORG_VIEW_BILLING_COMPANIES = "org:view_billing_companies"
PERM_ORG_MANAGE_BILLING_COMPANIES = "org:manage_billing_companies"
PERM_ORG_VIEW_MANAGEMENT_GROUPS = "org:view_management_groups"
PERM_ORG_MANAGE_MANAGEMENT_GROUPS = "org:manage_management_groups"

# ── Reporting permissions ─────────────────────────────────────────────────────
PERM_REPORTS_BILLING = "reports:billing"
PERM_REPORTS_CLINICAL = "reports:clinical"
PERM_REPORTS_OPERATIONAL = "reports:operational"

# ── Router-level shorthand aliases (used by require_permission() in routers) ──
# These map to the granular permissions above — included in role lists below.
PERM_PATIENTS_READ    = "patients:read"    # alias for patients:view
PERM_PATIENTS_WRITE   = "patients:write"   # alias for patients:create + edit
PERM_CLAIMS_READ      = "claims:read"      # alias for billing:view_claims
PERM_CLAIMS_WRITE     = "claims:write"     # alias for billing:submit/correct_claims
PERM_MASTER_DATA_READ = "master_data:read" # alias for settings:view

# ── Role → permission sets ────────────────────────────────────────────────────

ROLE_PERMISSIONS: dict[str, list[str]] = {
    # ── Clinic roles ──────────────────────────────────────────────────────────
    "front_desk": [
        PERM_PATIENTS_VIEW, PERM_PATIENTS_CREATE, PERM_PATIENTS_EDIT_DEMOGRAPHICS,
        PERM_PATIENTS_EDIT_INSURANCE,
        PERM_SCHEDULE_VIEW, PERM_SCHEDULE_BOOK, PERM_SCHEDULE_CANCEL,
        PERM_ELIGIBILITY_CHECK, PERM_ELIGIBILITY_VIEW,
        PERM_DOCUMENTS_UPLOAD, PERM_DOCUMENTS_VIEW,
        PERM_BILLING_VIEW_CHARGES, PERM_BILLING_PATIENT_PAYMENTS,
        PERM_SETTINGS_VIEW,
    ],
    "medical_assistant": [
        PERM_PATIENTS_VIEW, PERM_PATIENTS_EDIT_DEMOGRAPHICS,
        PERM_SCHEDULE_VIEW,
        PERM_CLINICAL_ROOM_PATIENT, PERM_CLINICAL_VIEW_NOTES, PERM_CLINICAL_VIEW_RESULTS,
        PERM_CLINICAL_EDIT_MEDICATIONS, PERM_CLINICAL_EDIT_ALLERGIES,
        PERM_CLINICAL_PLACE_ORDERS, PERM_CLINICAL_BODY_MAP,
        PERM_ELIGIBILITY_CHECK, PERM_ELIGIBILITY_VIEW,
        PERM_DOCUMENTS_UPLOAD, PERM_DOCUMENTS_VIEW,
        PERM_SETTINGS_VIEW,
    ],
    "nurse": [
        PERM_PATIENTS_VIEW, PERM_PATIENTS_EDIT_DEMOGRAPHICS,
        PERM_SCHEDULE_VIEW,
        PERM_CLINICAL_ROOM_PATIENT, PERM_CLINICAL_VIEW_NOTES, PERM_CLINICAL_DRAFT_NOTES,
        PERM_CLINICAL_VIEW_RESULTS, PERM_CLINICAL_EDIT_MEDICATIONS, PERM_CLINICAL_EDIT_ALLERGIES,
        PERM_CLINICAL_EDIT_PROBLEMS, PERM_CLINICAL_PLACE_ORDERS, PERM_CLINICAL_BODY_MAP,
        PERM_ELIGIBILITY_CHECK, PERM_ELIGIBILITY_VIEW,
        PERM_DOCUMENTS_UPLOAD, PERM_DOCUMENTS_VIEW,
        PERM_BILLING_PATIENT_PAYMENTS,
        PERM_SETTINGS_VIEW,
    ],
    "scribe": [
        PERM_PATIENTS_VIEW,
        PERM_CLINICAL_VIEW_NOTES, PERM_CLINICAL_DRAFT_NOTES, PERM_CLINICAL_VIEW_RESULTS,
        PERM_DOCUMENTS_VIEW,
    ],
    "doctor": [
        # Full clinical access
        PERM_PATIENTS_VIEW, PERM_PATIENTS_CREATE, PERM_PATIENTS_EDIT_DEMOGRAPHICS,
        PERM_PATIENTS_EDIT_INSURANCE, PERM_PATIENTS_VIEW_PHI,
        PERM_SCHEDULE_VIEW, PERM_SCHEDULE_BOOK,
        PERM_CLINICAL_ROOM_PATIENT, PERM_CLINICAL_VIEW_NOTES, PERM_CLINICAL_DRAFT_NOTES,
        PERM_CLINICAL_SIGN_NOTES, PERM_CLINICAL_EDIT_PROBLEMS, PERM_CLINICAL_EDIT_MEDICATIONS,
        PERM_CLINICAL_EDIT_ALLERGIES, PERM_CLINICAL_PLACE_ORDERS, PERM_CLINICAL_SIGN_ORDERS,
        PERM_CLINICAL_PRESCRIBE, PERM_CLINICAL_VIEW_RESULTS, PERM_CLINICAL_RELEASE_RESULTS,
        PERM_CLINICAL_BODY_MAP,
        PERM_ELIGIBILITY_CHECK, PERM_ELIGIBILITY_VIEW,
        PERM_DOCUMENTS_UPLOAD, PERM_DOCUMENTS_VIEW,
        PERM_BILLING_VIEW_CHARGES, PERM_BILLING_VIEW_CLAIMS,
        PERM_SETTINGS_VIEW,
    ],
    "billing": [
        PERM_PATIENTS_VIEW, PERM_PATIENTS_EDIT_INSURANCE,
        PERM_BILLING_VIEW_CHARGES, PERM_BILLING_ENTER_CHARGES, PERM_BILLING_EDIT_CHARGES,
        PERM_BILLING_VIEW_CLAIMS, PERM_BILLING_SUBMIT_CLAIMS, PERM_BILLING_CORRECT_CLAIMS,
        PERM_BILLING_POST_PAYMENTS, PERM_BILLING_POST_ADJUSTMENTS,
        PERM_BILLING_WORK_DENIALS, PERM_BILLING_FILE_APPEALS,
        PERM_BILLING_VIEW_AR, PERM_BILLING_VIEW_ERA, PERM_BILLING_IMPORT_ERA,
        PERM_BILLING_PATIENT_STATEMENTS, PERM_BILLING_PATIENT_PAYMENTS,
        PERM_ELIGIBILITY_CHECK, PERM_ELIGIBILITY_VIEW,
        PERM_DOCUMENTS_UPLOAD, PERM_DOCUMENTS_VIEW,
        PERM_REPORTS_BILLING,
        PERM_SETTINGS_VIEW,
    ],
    "supervisor": [
        # Billing + management of clinic staff
        PERM_PATIENTS_VIEW, PERM_PATIENTS_EDIT_INSURANCE,
        PERM_SCHEDULE_VIEW, PERM_SCHEDULE_MANAGE,
        PERM_BILLING_VIEW_CHARGES, PERM_BILLING_ENTER_CHARGES, PERM_BILLING_EDIT_CHARGES,
        PERM_BILLING_VIEW_CLAIMS, PERM_BILLING_SUBMIT_CLAIMS, PERM_BILLING_CORRECT_CLAIMS,
        PERM_BILLING_POST_PAYMENTS, PERM_BILLING_POST_ADJUSTMENTS,
        PERM_BILLING_WRITE_OFF, PERM_BILLING_ISSUE_REFUNDS,
        PERM_BILLING_WORK_DENIALS, PERM_BILLING_FILE_APPEALS,
        PERM_BILLING_VIEW_AR, PERM_BILLING_VIEW_ERA, PERM_BILLING_IMPORT_ERA,
        PERM_BILLING_PATIENT_STATEMENTS, PERM_BILLING_PATIENT_PAYMENTS,
        PERM_ELIGIBILITY_CHECK, PERM_ELIGIBILITY_VIEW,
        PERM_DOCUMENTS_UPLOAD, PERM_DOCUMENTS_VIEW,
        PERM_REPORTS_BILLING, PERM_REPORTS_OPERATIONAL,
        PERM_SETTINGS_VIEW, PERM_SETTINGS_MANAGE_USERS, PERM_SETTINGS_MANAGE_PROVIDERS,
    ],
    "admin": [
        # Full clinic admin
        PERM_PATIENTS_VIEW, PERM_PATIENTS_CREATE, PERM_PATIENTS_EDIT_DEMOGRAPHICS,
        PERM_PATIENTS_EDIT_INSURANCE, PERM_PATIENTS_VIEW_PHI, PERM_PATIENTS_MERGE,
        PERM_SCHEDULE_VIEW, PERM_SCHEDULE_BOOK, PERM_SCHEDULE_CANCEL, PERM_SCHEDULE_MANAGE,
        PERM_CLINICAL_VIEW_NOTES, PERM_CLINICAL_VIEW_RESULTS, PERM_CLINICAL_BODY_MAP,
        PERM_BILLING_VIEW_CHARGES, PERM_BILLING_ENTER_CHARGES, PERM_BILLING_EDIT_CHARGES,
        PERM_BILLING_VIEW_CLAIMS, PERM_BILLING_SUBMIT_CLAIMS, PERM_BILLING_CORRECT_CLAIMS,
        PERM_BILLING_POST_PAYMENTS, PERM_BILLING_POST_ADJUSTMENTS,
        PERM_BILLING_WRITE_OFF, PERM_BILLING_ISSUE_REFUNDS,
        PERM_BILLING_WORK_DENIALS, PERM_BILLING_FILE_APPEALS,
        PERM_BILLING_VIEW_AR, PERM_BILLING_VIEW_ERA, PERM_BILLING_IMPORT_ERA,
        PERM_BILLING_PATIENT_STATEMENTS, PERM_BILLING_PATIENT_PAYMENTS,
        PERM_ELIGIBILITY_CHECK, PERM_ELIGIBILITY_VIEW,
        PERM_DOCUMENTS_UPLOAD, PERM_DOCUMENTS_VIEW, PERM_DOCUMENTS_DELETE,
        PERM_REPORTS_BILLING, PERM_REPORTS_CLINICAL, PERM_REPORTS_OPERATIONAL,
        PERM_SETTINGS_VIEW, PERM_SETTINGS_EDIT_PRACTICE, PERM_SETTINGS_MANAGE_USERS,
        PERM_SETTINGS_MANAGE_PROVIDERS, PERM_SETTINGS_MANAGE_PAYERS,
        PERM_SETTINGS_MANAGE_FEE_SCHEDULES, PERM_SETTINGS_MANAGE_ROLES,
        PERM_ORG_VIEW_CLINICS,
    ],

    # ── Billing company roles ──────────────────────────────────────────────────
    "charge_entry": [
        PERM_PATIENTS_VIEW, PERM_PATIENTS_EDIT_INSURANCE,
        PERM_BILLING_VIEW_CHARGES, PERM_BILLING_ENTER_CHARGES, PERM_BILLING_EDIT_CHARGES,
        PERM_BILLING_VIEW_CLAIMS,
        PERM_ELIGIBILITY_VIEW, PERM_DOCUMENTS_VIEW,
        PERM_SETTINGS_VIEW,
    ],
    "coder": [
        PERM_PATIENTS_VIEW,
        PERM_CLINICAL_VIEW_NOTES, PERM_CLINICAL_VIEW_RESULTS,
        PERM_BILLING_VIEW_CHARGES, PERM_BILLING_ENTER_CHARGES, PERM_BILLING_EDIT_CHARGES,
        PERM_BILLING_VIEW_CLAIMS,
        PERM_DOCUMENTS_VIEW,
        PERM_SETTINGS_VIEW,
    ],
    "claim_submit": [
        PERM_PATIENTS_VIEW, PERM_PATIENTS_EDIT_INSURANCE,
        PERM_BILLING_VIEW_CHARGES, PERM_BILLING_VIEW_CLAIMS,
        PERM_BILLING_SUBMIT_CLAIMS, PERM_BILLING_CORRECT_CLAIMS,
        PERM_BILLING_VIEW_AR,
        PERM_ELIGIBILITY_CHECK, PERM_ELIGIBILITY_VIEW,
        PERM_DOCUMENTS_VIEW,
        PERM_SETTINGS_VIEW,
    ],
    "payment_poster": [
        PERM_PATIENTS_VIEW,
        PERM_BILLING_VIEW_CLAIMS, PERM_BILLING_VIEW_AR,
        PERM_BILLING_POST_PAYMENTS, PERM_BILLING_POST_ADJUSTMENTS,
        PERM_BILLING_VIEW_ERA, PERM_BILLING_IMPORT_ERA,
        PERM_BILLING_PATIENT_STATEMENTS, PERM_BILLING_PATIENT_PAYMENTS,
        PERM_DOCUMENTS_VIEW,
        PERM_SETTINGS_VIEW,
    ],
    "denial_specialist": [
        PERM_PATIENTS_VIEW,
        PERM_CLINICAL_VIEW_NOTES,
        PERM_BILLING_VIEW_CHARGES, PERM_BILLING_VIEW_CLAIMS, PERM_BILLING_CORRECT_CLAIMS,
        PERM_BILLING_VIEW_AR, PERM_BILLING_VIEW_ERA,
        PERM_BILLING_WORK_DENIALS, PERM_BILLING_FILE_APPEALS,
        PERM_DOCUMENTS_VIEW, PERM_DOCUMENTS_UPLOAD,
        PERM_SETTINGS_VIEW,
    ],
    "ar_specialist": [
        PERM_PATIENTS_VIEW,
        PERM_BILLING_VIEW_CHARGES, PERM_BILLING_VIEW_CLAIMS, PERM_BILLING_CORRECT_CLAIMS,
        PERM_BILLING_VIEW_AR, PERM_BILLING_VIEW_ERA,
        PERM_BILLING_WORK_DENIALS, PERM_BILLING_FILE_APPEALS,
        PERM_REPORTS_BILLING,
        PERM_DOCUMENTS_VIEW,
        PERM_SETTINGS_VIEW,
    ],
    "patient_billing": [
        PERM_PATIENTS_VIEW,
        PERM_BILLING_VIEW_CLAIMS, PERM_BILLING_VIEW_AR,
        PERM_BILLING_PATIENT_STATEMENTS, PERM_BILLING_PATIENT_PAYMENTS,
        PERM_BILLING_ISSUE_REFUNDS,
        PERM_DOCUMENTS_VIEW,
        PERM_SETTINGS_VIEW,
    ],
    "billing_manager": [
        # All billing permissions + approvals + reporting
        PERM_PATIENTS_VIEW, PERM_PATIENTS_EDIT_INSURANCE,
        PERM_BILLING_VIEW_CHARGES, PERM_BILLING_ENTER_CHARGES, PERM_BILLING_EDIT_CHARGES,
        PERM_BILLING_VIEW_CLAIMS, PERM_BILLING_SUBMIT_CLAIMS, PERM_BILLING_CORRECT_CLAIMS,
        PERM_BILLING_POST_PAYMENTS, PERM_BILLING_POST_ADJUSTMENTS,
        PERM_BILLING_WRITE_OFF, PERM_BILLING_ISSUE_REFUNDS,
        PERM_BILLING_WORK_DENIALS, PERM_BILLING_FILE_APPEALS,
        PERM_BILLING_VIEW_AR, PERM_BILLING_VIEW_ERA, PERM_BILLING_IMPORT_ERA,
        PERM_BILLING_PATIENT_STATEMENTS, PERM_BILLING_PATIENT_PAYMENTS,
        PERM_CLINICAL_VIEW_NOTES,
        PERM_ELIGIBILITY_CHECK, PERM_ELIGIBILITY_VIEW,
        PERM_DOCUMENTS_VIEW, PERM_DOCUMENTS_UPLOAD,
        PERM_REPORTS_BILLING, PERM_REPORTS_OPERATIONAL,
        PERM_SETTINGS_VIEW, PERM_SETTINGS_MANAGE_USERS,
        PERM_ORG_VIEW_CLINICS,
    ],
    "billing_admin": [
        # Full billing access across all clinics in the company + setup new clinics
        PERM_PATIENTS_VIEW, PERM_PATIENTS_EDIT_INSURANCE,
        PERM_BILLING_VIEW_CHARGES, PERM_BILLING_ENTER_CHARGES, PERM_BILLING_EDIT_CHARGES,
        PERM_BILLING_VIEW_CLAIMS, PERM_BILLING_SUBMIT_CLAIMS, PERM_BILLING_CORRECT_CLAIMS,
        PERM_BILLING_POST_PAYMENTS, PERM_BILLING_POST_ADJUSTMENTS,
        PERM_BILLING_WRITE_OFF, PERM_BILLING_ISSUE_REFUNDS,
        PERM_BILLING_WORK_DENIALS, PERM_BILLING_FILE_APPEALS,
        PERM_BILLING_VIEW_AR, PERM_BILLING_VIEW_ERA, PERM_BILLING_IMPORT_ERA,
        PERM_BILLING_PATIENT_STATEMENTS, PERM_BILLING_PATIENT_PAYMENTS,
        PERM_CLINICAL_VIEW_NOTES,
        PERM_ELIGIBILITY_CHECK, PERM_ELIGIBILITY_VIEW,
        PERM_DOCUMENTS_VIEW, PERM_DOCUMENTS_UPLOAD,
        PERM_REPORTS_BILLING, PERM_REPORTS_CLINICAL, PERM_REPORTS_OPERATIONAL,
        PERM_SETTINGS_VIEW, PERM_SETTINGS_EDIT_PRACTICE, PERM_SETTINGS_MANAGE_USERS,
        PERM_SETTINGS_MANAGE_PROVIDERS, PERM_SETTINGS_MANAGE_PAYERS,
        PERM_SETTINGS_MANAGE_FEE_SCHEDULES,
        PERM_ORG_VIEW_CLINICS, PERM_ORG_MANAGE_CLINICS,
        PERM_ORG_VIEW_BILLING_COMPANIES, PERM_ORG_MANAGE_BILLING_COMPANIES,
    ],

    # ── Management group roles ─────────────────────────────────────────────────
    "mgmt_viewer": [
        PERM_PATIENTS_VIEW,
        PERM_BILLING_VIEW_CLAIMS, PERM_BILLING_VIEW_AR,
        PERM_REPORTS_BILLING, PERM_REPORTS_OPERATIONAL,
        PERM_ORG_VIEW_CLINICS, PERM_ORG_VIEW_BILLING_COMPANIES, PERM_ORG_VIEW_MANAGEMENT_GROUPS,
        PERM_SETTINGS_VIEW,
    ],
    "mgmt_admin": [
        # Everything — can create/configure clinics, billing companies, all settings
        PERM_PATIENTS_VIEW, PERM_PATIENTS_EDIT_INSURANCE,
        PERM_BILLING_VIEW_CHARGES, PERM_BILLING_VIEW_CLAIMS, PERM_BILLING_VIEW_AR,
        PERM_BILLING_VIEW_ERA, PERM_BILLING_IMPORT_ERA,
        PERM_BILLING_SUBMIT_CLAIMS, PERM_BILLING_CORRECT_CLAIMS,
        PERM_BILLING_POST_PAYMENTS, PERM_BILLING_POST_ADJUSTMENTS,
        PERM_BILLING_WRITE_OFF, PERM_BILLING_ISSUE_REFUNDS,
        PERM_BILLING_WORK_DENIALS, PERM_BILLING_FILE_APPEALS,
        PERM_BILLING_PATIENT_STATEMENTS, PERM_BILLING_PATIENT_PAYMENTS,
        PERM_ELIGIBILITY_CHECK, PERM_ELIGIBILITY_VIEW,
        PERM_DOCUMENTS_VIEW, PERM_DOCUMENTS_UPLOAD, PERM_DOCUMENTS_DELETE,
        PERM_REPORTS_BILLING, PERM_REPORTS_CLINICAL, PERM_REPORTS_OPERATIONAL,
        PERM_SETTINGS_VIEW, PERM_SETTINGS_EDIT_PRACTICE, PERM_SETTINGS_MANAGE_USERS,
        PERM_SETTINGS_MANAGE_PROVIDERS, PERM_SETTINGS_MANAGE_PAYERS,
        PERM_SETTINGS_MANAGE_FEE_SCHEDULES, PERM_SETTINGS_MANAGE_ROLES,
        PERM_ORG_VIEW_CLINICS, PERM_ORG_MANAGE_CLINICS,
        PERM_ORG_VIEW_BILLING_COMPANIES, PERM_ORG_MANAGE_BILLING_COMPANIES,
        PERM_ORG_VIEW_MANAGEMENT_GROUPS, PERM_ORG_MANAGE_MANAGEMENT_GROUPS,
    ],
}


def get_permissions_for_role(role: str) -> list[str]:
    """Return the permission list for a given role name, including router-level aliases."""
    base = ROLE_PERMISSIONS.get(role, [])
    aliases: list[str] = []
    base_set = set(base)
    if PERM_PATIENTS_VIEW in base_set or PERM_PATIENTS_CREATE in base_set:
        aliases.append(PERM_PATIENTS_READ)
    if PERM_PATIENTS_CREATE in base_set or PERM_PATIENTS_EDIT_DEMOGRAPHICS in base_set or PERM_PATIENTS_EDIT_INSURANCE in base_set:
        aliases.append(PERM_PATIENTS_WRITE)
    if PERM_BILLING_VIEW_CLAIMS in base_set:
        aliases.append(PERM_CLAIMS_READ)
    if PERM_BILLING_SUBMIT_CLAIMS in base_set or PERM_BILLING_CORRECT_CLAIMS in base_set:
        aliases.append(PERM_CLAIMS_WRITE)
    if PERM_SETTINGS_VIEW in base_set:
        aliases.append(PERM_MASTER_DATA_READ)
    return base + aliases


def get_all_permissions_for_user(
    clinic_role: str | None = None,
    billing_role: str | None = None,
    mgmt_role: str | None = None,
    is_superuser: bool = False,
) -> set[str]:
    """Aggregate all permissions a user has across their assigned roles."""
    if is_superuser:
        return set(p for perms in ROLE_PERMISSIONS.values() for p in perms)
    perms: set[str] = set()
    for role in [clinic_role, billing_role, mgmt_role]:
        if role:
            perms.update(get_permissions_for_role(role))
    return perms
